### PR TITLE
RAD-5573 Improve scheduling and validation logic for Schedule Object

### PR DESCRIPTION
**Pull request by MertCingoz**
Addressing scheduling issues discussed in #97

### CODE REVIEW

**Review by terrypacker — APPROVED** [review]
Looks good, had a discussion with @MertCingoz and I am happy with these changes.

**Comment by kishorevenki** [comment]
I created my application with Schedule Object like the below:
ScheduleObject Sch1 = new ScheduleObject(localDevice, 1, "Schedule_1", 
                effectivePeriod, weeklySchedule, exceptionSchedule, new Real(10f), 
                sequenceDOPR, priorityForWriting.intValue(), false);
Sch1.updatePresentValue();

I have got the above error message:
The method updatePresentValue() from the type ScheduleObject is not visible

So I feel updatePresentValue() for Calendar and Schedule object should be made public.

**Comment by MertCingoz** [comment]
@kishorevenki why did you need to call this method on your code?

If value is not correct and you need to trigger update, then we need to focus why it is not correct instead of making this method to public.

**Comment by kishorevenki** [comment]
1. "If value is not correct and you need to trigger update" - how to trigger update?
2. Lets consider the below configurations for Schedule Object:

-     Schedule Object, so is configured with Exception Schedule = Null; Weekly Schedule = Monday to Sunday (8:00AM, 20.00); Schedule Default = 23.0
- In the above configuration every day from 8:00 AM till EOD the so.PV will be 20
- Assume that at 23:59 there are multiple RP requests for so.PV. 
- For the above couple of requests, the value will be 20 as long as the time is lesser than 23:59:59. 
- But once the time crosses 23:59:59, the value should be 23 which will not happen automatically. In the application we need to explicitly make so to update its PV by calling the method updatePresentValue() which in turn automatically set the PV of DOPR (Device Object Property Ref). 
- Same result will happen when the time reaches at 7:59:59. 
- Because of the above reasons and similar site conditions, updatePresentValue needs to be made Public. 
- Please let me know if any other method to make schedule Engine to calculate its PV from the application.

**Comment by MertCingoz** [comment]
@kishorevenki thank you for pointing the issue. There were issues around time format and should be fixed here #101.

So you don't need to trigger update method manually.

I think if you really want to trigger force update you need to use WP for any of following properties.
> PropertyIdentifier.effectivePeriod
> PropertyIdentifier.weeklySchedule
> PropertyIdentifier.exceptionSchedule
> PropertyIdentifier.scheduleDefault

**Comment by kishorevenki** [comment]
@MertCingoz 
The test will fail in multiple situations as I mentioned above. Hence its required for the application to call  updatePresentValue() of Schedule and Calendar Object. 
You can notice the same by creating an application and testing the schedule object. 
Updating of Scheduling and Calendar is required when the controller receives
a) TimeSynch
b) RP / RPM request
c) Schedule will update automatically when it receives WP for the above properties as mentioned. 

If you need I can create a separate issue for the same.

**Comment by MertCingoz** [comment]
> The test will fail in multiple situations as I mentioned above. Hence its required for the application to call updatePresentValue() of Schedule and Calendar Object. You can notice the same by creating an application and testing the schedule object.

`fullTest` seems to be very complex than your example and still be able to pass without need of updatePresentValue call.

Did you actually check what is changed? Scheduler is completely broken since beginning, it is scheduling next update 30-40 years later instead of hours-minutes.

Please try your case on top of fix and let me know if it works or not.

**Pull request merged**
